In [4]:
!pip install window_ops
!pip install statsforecast
!pip install mlforecast
!pip install lightgbm

Requirement already satisfied: window_ops in /usr/local/lib/python3.12/dist-packages (0.0.15)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from window_ops) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from window_ops) (2.0.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->window_ops) (0.43.0)
Requirement already satisfied: statsforecast in /usr/local/lib/python3.12/dist-packages (2.0.3)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from statsforecast) (3.1.2)
Requirement already satisfied: coreforecast>=0.0.12 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (0.0.17)
Requirement already satisfied: numba>=0.55.0 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (0.60.0)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (2.0.2)
Requirement already satisfied: pandas>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (2.2.2)
Requirement already satisfied: scipy<1.16.0,>=1.7.3 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (1.15.3)
Requirement already satisfied: statsmodels>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (0.14.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from statsforecast) (4.67.1)
Requirement already satisfied: fugue>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (0.9.7)
Requirement already satisfied: utilsforecast>=0.1.4 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (0.2.16)
Requirement already satisfied: threadpoolctl>=3 in /usr/local/lib/python3.12/dist-packages (from statsforecast) (3.6.0)
Requirement already satisfied: triad>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from fugue>=0.8.1->statsforecast) (1.0.2)
Requirement already satisfied: adagio>=0.2.6 in /usr/local/lib/python3.12/dist-packages (from fugue>=0.8.1->statsforecast) (0.2.6)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.55.0->statsforecast) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->statsforecast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->statsforecast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.5->statsforecast) (2026.1)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.2->statsforecast) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.13.2->statsforecast) (26.1)
Requirement already satisfied: narwhals>=2.0 in /usr/local/lib/python3.12/dist-packages (from utilsforecast>=0.1.4->statsforecast) (2.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.5->statsforecast) (1.17.0)
Requirement already satisfied: pyarrow>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from triad>=1.0.1->fugue>=0.8.1->statsforecast) (18.1.0)
Requirement already satisfied: fsspec>=2022.5.0 in /usr/local/lib/python3.12/dist-packages (from triad>=1.0.1->fugue>=0.8.1->statsforecast) (2025.3.0)
Requirement already satisfied: mlforecast in /usr/local/lib/python3.12/dist-packages (1.0.31)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from mlforecast) (3.1.2)
Requirement already satisfied: coreforecast>=0.0.15 in /usr/local/lib/python3.12/dist-packages (from mlforecast) (0.0.17)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from mlforecast) (2025.3.0)
Requirement already satisfied: narwhals in /usr/local/lib/python3.12/dist-packages (from mlforecast) (2.20.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from mlforecast) (4.8.0)
Requirement already satisfied: pandas<3.0 in /usr/local/lib/python3.12/dist-packages (from mlforecast) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from mlforecast) (1.6.1)
Requirement already satisfied: utilsforecast>=0.2.9 in /usr/local/lib/python3.12/dist-packages (from mlforecast) (0.2.16)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from coreforecast>=0.0.15->mlforecast) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->mlforecast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->mlforecast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->mlforecast) (2026.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from utilsforecast>=0.2.9->mlforecast) (26.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->mlforecast) (6.0.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->mlforecast) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->mlforecast) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->mlforecast) (3.6.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->mlforecast) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->mlforecast) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0->mlforecast) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->mlforecast) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->mlforecast) (3.0.3)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm) (1.15.3)

In [5]:
import pandas as pd
import numpy as np

from mlforecast import MLForecast
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor

from mlforecast.target_transforms import Differences
from window_ops.rolling import rolling_mean

from utilsforecast.evaluation import evaluate
from utilsforecast.losses import mae, rmse, mape, bias

In [6]:
df = pd.read_parquet('/content/sample_hotels-1.parquet')

df['ds'] = pd.to_datetime(df['ds'])

otb_cols = [f'otb_{i}' for i in range(28, 61) if f'otb_{i}' in df.columns]

df = df[['unique_id', 'ds', 'y', 'location_type', 'hotel_type'] + otb_cols]

df = df.query("unique_id not in ['hotel_77', 'hotel_28']")

In [7]:
#  the training set first
train_df = df.groupby('unique_id').head(-28).reset_index(drop=True)

#  dummy variables for categorical predictors
train_df_dummies = df.groupby('unique_id').apply(lambda x: x.iloc[:-28]).reset_index(drop=True)

# Identify the names of these new dummy columns for later use
dummies = [c for c in train_df_dummies if 'location_type_' in c or 'hotel_type_' in c]

/tmp/ipykernel_7178/3403269105.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  train_df_dummies = df.groupby('unique_id').apply(lambda x: x.iloc[:-28]).reset_index(drop=True)

In [8]:
ml_models = {
    'LGBM': LGBMRegressor(random_state=42, verbosity=-1),
    'RF': RandomForestRegressor(random_state=42)
}

In [9]:
ml = MLForecast(
    models=ml_models,
    freq='D',
    lags=[28, 29, 35],
    lag_transforms={
        28: [(rolling_mean, 7)]
    },
    target_transforms=[Differences([7])]


)

In [10]:
key_predictors = ['otb_28'] + dummies

cv_ml = ml.cross_validation(
    df=train_df_dummies[['unique_id', 'ds', 'y'] + key_predictors],
    h=28,
    n_windows=5,
    step_size=28,
    static_features=[]  # dummies are static, otb_28 is dynamic
)

In [11]:
eval_ml = evaluate(
    df = cv_ml,
    metrics = [mae, rmse, bias],
    models=['RF', 'LGBM']
)
eval_ml = eval_ml.drop(columns=['cutoff']).groupby(['unique_id','metric']).mean().reset_index()
eval_ml

    unique_id metric        RF      LGBM
0     hotel_0   bias  0.061236  0.052970
1     hotel_0    mae  0.207827  0.206011
2     hotel_0   rmse  0.247166  0.247536
3   hotel_105   bias -0.078062 -0.083798
4   hotel_105    mae  0.144859  0.150690
5   hotel_105   rmse  0.180292  0.188291
6   hotel_112   bias -0.063483 -0.056177
7   hotel_112    mae  0.131028  0.132579
8   hotel_112   rmse  0.157224  0.159616
9   hotel_126   bias  0.045586  0.052239
10  hotel_126    mae  0.113727  0.115696
11  hotel_126   rmse  0.143534  0.143706
12  hotel_133   bias  0.007821  0.007585
13  hotel_133    mae  0.153331  0.143824
14  hotel_133   rmse  0.187038  0.173387
15   hotel_14   bias -0.039458 -0.030095
16   hotel_14    mae  0.139123  0.130084
17   hotel_14   rmse  0.168584  0.158756
18   hotel_21   bias  0.049416  0.050578
19   hotel_21    mae  0.071715  0.068910
20   hotel_21   rmse  0.092404  0.088798
21   hotel_35   bias -0.080681 -0.088044
22   hotel_35    mae  0.168761  0.167207
23   hotel_35   rmse  0.195092  0.191761
24   hotel_42   bias -0.009582  0.014519
25   hotel_42    mae  0.302100  0.287123
26   hotel_42   rmse  0.377893  0.353711
27   hotel_49   bias  0.099281  0.099285
28   hotel_49    mae  0.124529  0.119238
29   hotel_49   rmse  0.143338  0.138886
30   hotel_56   bias  0.009798  0.008005
31   hotel_56    mae  0.067731  0.055967
32   hotel_56   rmse  0.089666  0.079196
33   hotel_63   bias  0.015059  0.026142
34   hotel_63    mae  0.203307  0.208834
35   hotel_63   rmse  0.251037  0.253966
36    hotel_7   bias  0.011993  0.009498
37    hotel_7    mae  0.122903  0.117999
38    hotel_7   rmse  0.148229  0.142332
39   hotel_70   bias -0.074441 -0.065186
40   hotel_70    mae  0.122503  0.111298
41   hotel_70   rmse  0.148895  0.132343
42   hotel_84   bias  0.063748  0.072206
43   hotel_84    mae  0.215308  0.209782
44   hotel_84   rmse  0.266081  0.259913
45   hotel_91   bias -0.011508 -0.015797
46   hotel_91    mae  0.191146  0.191541
47   hotel_91   rmse  0.237551  0.235396
48   hotel_98   bias -0.036707 -0.036555
49   hotel_98    mae  0.158589  0.156084
50   hotel_98   rmse  0.193444  0.198577

In [12]:
#without mape
eval_ml = evaluate(
    df = cv_ml,
    metrics = [mae, rmse, bias],
    models=['RF', 'LGBM']
)
eval_ml = eval_ml.drop(columns=['cutoff']).groupby(['unique_id','metric']).mean().reset_index()
eval_ml

    unique_id metric        RF      LGBM
0     hotel_0   bias  0.061236  0.052970
1     hotel_0    mae  0.207827  0.206011
2     hotel_0   rmse  0.247166  0.247536
3   hotel_105   bias -0.078062 -0.083798
4   hotel_105    mae  0.144859  0.150690
5   hotel_105   rmse  0.180292  0.188291
6   hotel_112   bias -0.063483 -0.056177
7   hotel_112    mae  0.131028  0.132579
8   hotel_112   rmse  0.157224  0.159616
9   hotel_126   bias  0.045586  0.052239
10  hotel_126    mae  0.113727  0.115696
11  hotel_126   rmse  0.143534  0.143706
12  hotel_133   bias  0.007821  0.007585
13  hotel_133    mae  0.153331  0.143824
14  hotel_133   rmse  0.187038  0.173387
15   hotel_14   bias -0.039458 -0.030095
16   hotel_14    mae  0.139123  0.130084
17   hotel_14   rmse  0.168584  0.158756
18   hotel_21   bias  0.049416  0.050578
19   hotel_21    mae  0.071715  0.068910
20   hotel_21   rmse  0.092404  0.088798
21   hotel_35   bias -0.080681 -0.088044
22   hotel_35    mae  0.168761  0.167207
23   hotel_35   rmse  0.195092  0.191761
24   hotel_42   bias -0.009582  0.014519
25   hotel_42    mae  0.302100  0.287123
26   hotel_42   rmse  0.377893  0.353711
27   hotel_49   bias  0.099281  0.099285
28   hotel_49    mae  0.124529  0.119238
29   hotel_49   rmse  0.143338  0.138886
30   hotel_56   bias  0.009798  0.008005
31   hotel_56    mae  0.067731  0.055967
32   hotel_56   rmse  0.089666  0.079196
33   hotel_63   bias  0.015059  0.026142
34   hotel_63    mae  0.203307  0.208834
35   hotel_63   rmse  0.251037  0.253966
36    hotel_7   bias  0.011993  0.009498
37    hotel_7    mae  0.122903  0.117999
38    hotel_7   rmse  0.148229  0.142332
39   hotel_70   bias -0.074441 -0.065186
40   hotel_70    mae  0.122503  0.111298
41   hotel_70   rmse  0.148895  0.132343
42   hotel_84   bias  0.063748  0.072206
43   hotel_84    mae  0.215308  0.209782
44   hotel_84   rmse  0.266081  0.259913
45   hotel_91   bias -0.011508 -0.015797
46   hotel_91    mae  0.191146  0.191541
47   hotel_91   rmse  0.237551  0.235396
48   hotel_98   bias -0.036707 -0.036555
49   hotel_98    mae  0.158589  0.156084
50   hotel_98   rmse  0.193444  0.198577

In [13]:
#with mape
eval_ml = evaluate(
    df = cv_ml,
    metrics = [mae, rmse,mape, bias],
    models=['RF', 'LGBM']
)
eval_ml = eval_ml.drop(columns=['cutoff']).groupby(['unique_id','metric']).mean().reset_index()
eval_ml

    unique_id metric        RF      LGBM
0     hotel_0   bias  0.061236  0.052970
1     hotel_0    mae  0.207827  0.206011
2     hotel_0   mape  0.328947  0.327884
3     hotel_0   rmse  0.247166  0.247536
4   hotel_105   bias -0.078062 -0.083798
..        ...    ...       ...       ...
63   hotel_91   rmse  0.237551  0.235396
64   hotel_98   bias -0.036707 -0.036555
65   hotel_98    mae  0.158589  0.156084
66   hotel_98   mape  0.779299  0.752020
67   hotel_98   rmse  0.193444  0.198577

[68 rows x 4 columns]

In [14]:
eval_ml['best_model'] = eval_ml[['RF', 'LGBM']].idxmin(axis=1)

In [15]:
win_counts = (
    eval_ml
    .groupby(['metric', 'best_model'])
    .size()
    .reset_index(name='wins')
)

display(win_counts)

  metric best_model  wins
0   bias       LGBM     7
1   bias         RF    10
2    mae       LGBM    12
3    mae         RF     5
4   mape       LGBM    11
5   mape         RF     6
6   rmse       LGBM    11
7   rmse         RF     6

In [16]:
ml_models = ['RF', 'LGBM']

In [17]:
metrics = ['mae', 'rmse', 'mape', 'bias']
summary_list = []

for m in metrics:
    wins = (
        eval_ml.query(f"metric == '{m}'")
        .assign(winner = lambda x: x[ml_models].idxmin(axis=1))
        ['winner'].value_counts()
    )
    summary_list.append(wins.rename(m.upper()))

# Merge into one summary DataFrame
win_summary_table = pd.concat(summary_list, axis=1).fillna(0).astype(int)
display(win_summary_table)

        MAE  RMSE  MAPE  BIAS
winner
LGBM     12    11    11     7
RF        5     6     6    10

##Tabpfn

In [23]:
#!pip install tabpfn

Requirement already satisfied: tabpfn in /usr/local/lib/python3.12/dist-packages (7.1.1)
Requirement already satisfied: torch>=2.5 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.0.2)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.6.1)
Requirement already satisfied: typing_extensions>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (4.15.0)
Requirement already satisfied: scipy>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.15.3)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.2.2)
Requirement already satisfied: einops>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.11.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.14.0)
Requirement already satisfied: eval-type-backport>=0.2.2 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (0.3.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.5.3)
Requirement already satisfied: tabpfn-common-utils>=0.2.13 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (0.2.21)
Requirement already satisfied: filelock>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (4.67.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (0.24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->tabpfn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->tabpfn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->tabpfn) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->tabpfn) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->tabpfn) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->tabpfn) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.10.1->tabpfn) (1.2.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.0->tabpfn) (3.6.0)
Requirement already satisfied: nvidia-ml-py>=13.590.48 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (13.595.45)
Requirement already satisfied: platformdirs>=4 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (4.9.6)
Requirement already satisfied: posthog>=6.7 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (7.14.0)
Requirement already satisfied: requests>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (2.33.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.5->tabpfn) (1.5.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (0.16.0)
Requirement already satisfied: backoff>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from posthog>=6.7->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from posthog>=6.7->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (1.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->tabpfn) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.5->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.5->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.5->tabpfn) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.5->tabpfn) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.19.0->tabpfn) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.19.0->tabpfn) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.19.0->tabpfn) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.19.0->tabpfn) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.19.0->tabpfn) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.19.0->tabpfn) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.19.0->tabpfn) (0.1.2)

In [27]:
from tabpfn import TabPFNRegressor
from mlforecast import MLForecast
from mlforecast.target_transforms import Differences

# 1. Initialize with specific arguments to avoid the "missing arguments" error
# TabPFN often expects a 'device' and 'n_estimators' or similar depending on version
# Use 'cuda' to specify GPU usage
tpfn_model = TabPFNRegressor(device='cuda')

# 2. Put it in your MLForecast object
fcst = MLForecast(
    models={
        'lgbm': LGBMRegressor(verbosity=-1),
        'tabpfn': tpfn_model  # Give it a string name in a dictionary
    },
    freq='D',
    lags=[1, 7, 14],
    date_features=['dayofweek', 'month']
)

In [20]:
#!pip install tabpfn-client

Requirement already satisfied: tabpfn-client in /usr/local/lib/python3.12/dist-packages (0.2.8)
Requirement already satisfied: backoff<=2.2.1,>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (2.2.1)
Requirement already satisfied: httpx<=0.28.1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (0.28.1)
Requirement already satisfied: omegaconf<=2.3.0,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (2.3.0)
Requirement already satisfied: pandas<=2.3.3,>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (2.2.2)
Requirement already satisfied: password-strength<=0.0.3.post2,>=0.0.3.post2 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (0.0.3.post2)
Requirement already satisfied: rich<=14.0.0,>=13.7.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (13.9.4)
Requirement already satisfied: scikit-learn<=1.6.1,>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (1.6.1)
Requirement already satisfied: sseclient-py<=1.8.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (1.8.0)
Requirement already satisfied: tqdm<=4.67.1,>=4.63.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (4.67.1)
Requirement already satisfied: typing-extensions<=4.15.0,>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (4.15.0)
Requirement already satisfied: xxhash<=3.6.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn-client) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<=0.28.1,>=0.25.0->httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<=0.28.1,>=0.25.0->httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<=0.28.1,>=0.25.0->httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<=0.28.1,>=0.25.0->httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<=0.28.1,>=0.25.0->httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (4.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf<=2.3.0,>=2.1.2->tabpfn-client) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from omegaconf<=2.3.0,>=2.1.2->tabpfn-client) (6.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas<=2.3.3,>=2.1.2->tabpfn-client) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<=2.3.3,>=2.1.2->tabpfn-client) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<=2.3.3,>=2.1.2->tabpfn-client) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<=2.3.3,>=2.1.2->tabpfn-client) (2026.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from password-strength<=0.0.3.post2,>=0.0.3.post2->tabpfn-client) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<=14.0.0,>=13.7.0->tabpfn-client) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<=14.0.0,>=13.7.0->tabpfn-client) (2.20.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<=1.6.1,>=1.3.1->tabpfn-client) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<=1.6.1,>=1.3.1->tabpfn-client) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<=1.6.1,>=1.3.1->tabpfn-client) (3.6.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<=0.28.1,>=0.25.0->tabpfn-client) (4.1.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<=14.0.0,>=13.7.0->tabpfn-client) (0.1.2)

In [28]:
# Convert object columns to categories so LightGBM can process them
train_df['location_type'] = train_df['location_type'].astype('category')
train_df['hotel_type'] = train_df['hotel_type'].astype('category')

# Set the TabPFN license token
import os
# Replace 'YOUR_API_KEY_HERE' with your actual API key obtained from https://ux.priorlabs.ai/account
os.environ["TABPFN_TOKEN"] = "YOUR_API_KEY_HERE" # not adding to public github, but created our own
# Allow TabPFN to run on CPU with large datasets
os.environ["TABPFN_ALLOW_CPU_LARGE_DATASET"] = "1"

# Now run your CV
cv_results = fcst.cross_validation(
    df=train_df,
    h=28,
    step_size=28,
    n_windows=5,
    static_features=['location_type', 'hotel_type'] # Include them here now that they are categories
)

In [31]:
evaluation_df = evaluate(
    cv_results,
    metrics=[mae, rmse],
    id_col='unique_id',
    target_col='y'
)

In [32]:
display(evaluation_df)

     unique_id     cutoff metric      lgbm    tabpfn
0      hotel_0 2023-01-13    mae  0.114761  0.118769
1    hotel_105 2023-01-13    mae  0.099072  0.096518
2    hotel_112 2023-01-13    mae  0.068157  0.066432
3    hotel_126 2023-01-13    mae  0.123044  0.114021
4    hotel_133 2023-01-13    mae  0.109622  0.092735
..         ...        ...    ...       ...       ...
165    hotel_7 2023-05-05   rmse  0.133192  0.125518
166   hotel_70 2023-05-05   rmse  0.174646  0.155329
167   hotel_84 2023-05-05   rmse  0.106588  0.104052
168   hotel_91 2023-05-05   rmse  0.117101  0.125570
169   hotel_98 2023-05-05   rmse  0.176741  0.135871

[170 rows x 5 columns]

In [33]:
# save to csv
evaluation_df.to_csv('TabPFN_output.csv', index=False)